#!/usr/bin/env python3
"""
FoodRAG query — ask "where to eat" against your ingested reviews.

Usage:
    python query.py "where should I get chilli crab tonight?"
    python query.py "best brunch cafes" --city "Kuala Lumpur"
    python query.py "new omakase worth booking" --region SG --k 8

Retrieval is semantic (vector search) with optional city/region filtering.
Answers are generated by Claude using ONLY the retrieved snippets, and every
recommendation is followed by its source link so you can verify and read more.
Retrieval works with no API key — you just get the raw ranked snippets instead.
"""
import argparse
import os
import textwrap

import chromadb
from sentence_transformers import SentenceTransformer

try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

try:
    import anthropic
except ImportError:
    anthropic = None

DB_PATH = "./chroma_db"
COLLECTION = "food_reviews"
EMBED_MODEL = "all-MiniLM-L6-v2"
LLM_MODEL = "claude-opus-4-8"

SYSTEM = """You are a local food guide for Malaysia and Singapore.
Answer the user's question using ONLY the numbered snippets provided.
Recommend specific places with a one-line reason each. If the snippets don't
cover the question, say so plainly rather than inventing places.
After each recommendation, cite the source in brackets like [Source name].
Keep it punchy and useful, like a friend who eats out constantly."""


def retrieve(question, k, region, city):
    embedder = SentenceTransformer(EMBED_MODEL)
    client = chromadb.PersistentClient(path=DB_PATH)
    coll = client.get_or_create_collection(COLLECTION)

    where = {}
    if region and city:
        where = {"$and": [{"region": region}, {"city": city}]}
    elif region:
        where = {"region": region}
    elif city:
        where = {"city": city}

    res = coll.query(
        query_embeddings=embedder.encode([question]).tolist(),
        n_results=k,
        where=where or None,
    )
    docs = res.get("documents", [[]])[0]
    metas = res.get("metadatas", [[]])[0]
    return list(zip(docs, metas))


def build_context(hits):
    blocks, sources = [], []
    for i, (doc, meta) in enumerate(hits, 1):
        blocks.append(f"[{i}] Source: {meta['source']} — {meta.get('title','')}\n"
                      f"URL: {meta['url']}\n{doc}")
        sources.append((meta["source"], meta["url"]))
    return "\n\n".join(blocks), sources


def answer(question, context):
    if anthropic is None or not os.getenv("ANTHROPIC_API_KEY"):
        return None  # signal: fall back to raw snippets
    client = anthropic.Anthropic()
    msg = client.messages.create(
        model=LLM_MODEL,
        max_tokens=800,
        system=SYSTEM,
        messages=[{
            "role": "user",
            "content": f"Question: {question}\n\nSnippets:\n{context}",
        }],
    )
    return "".join(b.text for b in msg.content if b.type == "text")


def main():
    ap = argparse.ArgumentParser(description="FoodRAG query (MY & SG).")
    ap.add_argument("question")
    ap.add_argument("--k", type=int, default=6, help="snippets to retrieve")
    ap.add_argument("--region", choices=["SG", "MY"], default=None)
    ap.add_argument("--city", default=None)
    args = ap.parse_args()

    hits = retrieve(args.question, args.k, args.region, args.city)
    if not hits:
        print("No matches yet — run ingest.py first, or widen your filters.")
        return

    context, sources = build_context(hits)
    reply = answer(args.question, context)

    if reply:
        print("\n" + reply + "\n")
    else:
        # No API key: show the raw retrieved evidence so it's still useful.
        print("\n(No ANTHROPIC_API_KEY set — showing raw retrieved snippets)\n")
        for doc, meta in hits:
            print(f"• {meta['source']} — {meta.get('title','') or meta['url']}")
            print(textwrap.fill(doc[:280], width=88, initial_indent="   ",
                                subsequent_indent="   "))
            print(f"   {meta['url']}\n")

    print("Sources:")
    for url, name in {u: n for n, u in sources}.items():   # de-duped by url
        print(f"  - {url}  ({name})")


if __name__ == "__main__":
    main()
