#!/usr/bin/env python3
"""
FoodRAG query — ask "where to eat" against your ingested reviews.

Usage:
    python query.py "where should I get chilli crab tonight?"
    python query.py "best brunch cafes" --city "Kuala Lumpur"
    python query.py "new omakase worth booking" --region SG --k 8

Retrieval is semantic (vector search) with optional city/region filtering.
Answers are generated by Claude using ONLY the retrieved snippets, and every
recommendation is followed by its source link so you can verify and read more.
Retrieval works with no API key — you just get the raw ranked snippets instead.

The retrieval/answer functions here are also imported by app.py (the Streamlit
UI), so they are written to be reusable and to accept pre-loaded models.
"""
import argparse
import math
import os
import textwrap

import chromadb
from sentence_transformers import SentenceTransformer

try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

try:
    import anthropic
except ImportError:
    anthropic = None

DB_PATH = "./chroma_db"
COLLECTION = "food_reviews"
EMBED_MODEL = "paraphrase-multilingual-MiniLM-L12-v2"  # 384-dim, ASEAN languages
LLM_MODEL = "claude-opus-4-8"

SYSTEM = """You are a local food guide for Malaysia and Singapore.
Answer the user's question using ONLY the numbered snippets provided.
Recommend specific places with a one-line reason each. If the snippets don't
cover the question, say so plainly rather than inventing places.
After each recommendation, cite the source in brackets like [Source name].
Keep it punchy and useful, like a friend who eats out constantly."""


# ── reusable building blocks (imported by app.py) ────────────────────────────
def get_embedder() -> SentenceTransformer:
    """Load the local embedding model (cache this in long-lived processes)."""
    return SentenceTransformer(EMBED_MODEL)


def get_collection():
    """Open the persistent Chroma collection (cache this too)."""
    client = chromadb.PersistentClient(path=DB_PATH)
    return client.get_or_create_collection(COLLECTION)


def build_where(region: str | None, city: str | None) -> dict | None:
    """Compose a Chroma metadata filter from optional region/city."""
    if region and city:
        return {"$and": [{"region": region}, {"city": city}]}
    if region:
        return {"region": region}
    if city:
        return {"city": city}
    return None


def haversine_km(lat1, lng1, lat2, lng2):
    """Great-circle distance in km between two lat/lng points."""
    r = 6371.0
    p1, p2 = math.radians(lat1), math.radians(lat2)
    dphi = math.radians(lat2 - lat1)
    dlmb = math.radians(lng2 - lng1)
    a = math.sin(dphi / 2) ** 2 + math.cos(p1) * math.cos(p2) * math.sin(dlmb / 2) ** 2
    return 2 * r * math.asin(math.sqrt(a))


def retrieve(question, k=6, region=None, city=None, embedder=None, coll=None,
             near=None, radius_km=None):
    """Semantic search; returns hit dicts {doc, meta, distance[, distance_km]}.

    When `near=(lat,lng)` is given, we over-fetch candidates, drop any without
    coordinates or outside `radius_km`, sort by proximity, and return the top k.
    Run enrich_geo.py first so chunks carry lat/lng.
    """
    embedder = embedder or get_embedder()
    coll = coll or get_collection()
    n = max(k * 8, 40) if near else k
    res = coll.query(
        query_embeddings=embedder.encode([question]).tolist(),
        n_results=n,
        where=build_where(region, city),
    )
    docs = res.get("documents", [[]])[0]
    metas = res.get("metadatas", [[]])[0]
    dists = res.get("distances", [[]])[0] or [None] * len(docs)
    hits = [{"doc": d, "meta": m, "distance": dist}
            for d, m, dist in zip(docs, metas, dists)]

    if near:
        lat0, lng0 = near
        geo_hits = []
        for h in hits:
            lat, lng = h["meta"].get("lat"), h["meta"].get("lng")
            if lat is None or lng is None:
                continue
            dkm = haversine_km(lat0, lng0, lat, lng)
            if radius_km is None or dkm <= radius_km:
                h["distance_km"] = dkm
                geo_hits.append(h)
        geo_hits.sort(key=lambda h: h["distance_km"])
        return geo_hits[:k]

    return hits


def build_context(hits: list[dict]):
    """Numbered context block + (source, url) list from retrieval hits."""
    blocks, sources = [], []
    for i, h in enumerate(hits, 1):
        meta = h["meta"]
        blocks.append(f"[{i}] Source: {meta['source']} — {meta.get('title','')}\n"
                      f"URL: {meta['url']}\n{h['doc']}")
        sources.append((meta["source"], meta["url"]))
    return "\n\n".join(blocks), sources


def has_api_key() -> bool:
    """True only if a *real* key is present — the .env.example placeholder
    ('sk-ant-...') must not count, or we'd 401 on every answer."""
    key = os.getenv("ANTHROPIC_API_KEY", "").strip()
    return anthropic is not None and bool(key) and "..." not in key


def answer(question, context):
    """Generate a cited answer with Claude, or None if no API key is available."""
    if not has_api_key():
        return None  # signal: fall back to raw snippets
    client = anthropic.Anthropic()
    msg = client.messages.create(
        model=LLM_MODEL,
        max_tokens=800,
        system=SYSTEM,
        messages=[{
            "role": "user",
            "content": f"Question: {question}\n\nSnippets:\n{context}",
        }],
    )
    return "".join(b.text for b in msg.content if b.type == "text")


# ── CLI ──────────────────────────────────────────────────────────────────────
def main():
    ap = argparse.ArgumentParser(description="FoodRAG query (MY & SG).")
    ap.add_argument("question")
    ap.add_argument("--k", type=int, default=6, help="snippets to retrieve")
    ap.add_argument("--region",
                    choices=["SG", "MY", "TH", "ID", "PH", "VN", "KH", "LA",
                             "MM", "BN", "ASEAN"],
                    default=None)
    ap.add_argument("--city", default=None)
    ap.add_argument("--near", default=None,
                    help='"lat,lng" to rank by proximity (run enrich_geo.py first)')
    ap.add_argument("--radius-km", type=float, default=None, dest="radius_km",
                    help="only include places within this many km of --near")
    args = ap.parse_args()

    near = None
    if args.near:
        try:
            lat_s, lng_s = args.near.split(",")
            near = (float(lat_s), float(lng_s))
        except ValueError:
            ap.error('--near must look like "3.1390,101.6869"')

    hits = retrieve(args.question, args.k, args.region, args.city,
                    near=near, radius_km=args.radius_km)
    if not hits:
        print("No matches yet — run ingest.py first, or widen your filters.")
        return

    context, sources = build_context(hits)
    try:
        reply = answer(args.question, context)
    except Exception as e:
        print(f"(answer generation failed: {type(e).__name__}: {e} — showing snippets)")
        reply = None

    if reply:
        print("\n" + reply + "\n")
    else:
        # No API key: show the raw retrieved evidence so it's still useful.
        print("\n(No ANTHROPIC_API_KEY set — showing raw retrieved snippets)\n")
        for h in hits:
            meta = h["meta"]
            near_tag = f"  [{h['distance_km']:.1f} km]" if "distance_km" in h else ""
            print(f"• {meta['source']} — {meta.get('title','') or meta['url']}{near_tag}")
            print(textwrap.fill(h["doc"][:280], width=88, initial_indent="   ",
                                subsequent_indent="   "))
            print(f"   {meta['url']}\n")

    print("Sources:")
    for url, name in {u: n for n, u in sources}.items():   # de-duped by url
        print(f"  - {url}  ({name})")


if __name__ == "__main__":
    main()
